language: python
python:
  - "3.6"

global:
  - APP_SETTING=testing

# Service for postgre database
services:
  - postgresql 

# command to install requirements
install:
  - pip install -r requirements.txt

before_script:
  - "psql -c 'CREATE DATABASE postgrestest;' -U postgres"

# command to run tests
script:
  - py.test --cov-report term --cov=app
  - coverage report

after_success:
- coveralls